version: "3"
services:

   
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: ecom
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/posgresql/data
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/code
      - pgdata:/code/pgdata
      - media:/code/media
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
volumes:
  pgdata:
  media: